DEBUG    root:conf.py:30 读数据库服务器配置文件/Users/yangjingkang/PycharmProjects/YJK_api-master/confs/db.conf成功，数据库信息是{'host': '172.16.9.128', 'db': 'wa_test', 'user': 'root', 'passwd': '123456'}
INFO     root:mysql.py:28 ===============>成功连接数据库,参数为：{'host': '172.16.9.128', 'db': 'wa_test', 'user': 'root', 'passwd': '123456'}<===================
INFO     root:preposition_fixture.py:29 *********************开始数据库连接*********************
INFO     root:preposition_fixture.py:44 ==========开始获取获取用户信息==========
INFO     root:preposition_fixture.py:47 ==========成功获取用户信息：admin,e10adc3949ba59abbe56e057f20f883e ==========
DEBUG    root:mysql.py:94 执行SQL语句=====>DELETE FROM info WHERE id=4<=====成功
DEBUG    root:mysql.py:94 执行SQL语句=====>DELETE FROM users WHERE id=4<=====成功
DEBUG    root:mysql.py:44 执行SQL语句=====>INSERT INTO users(id, username, password) VALUES(4, 'test01', md5('123456'))<=====成功
DEBUG    root:mysql.py:94 执行SQL语句=====>DELETE FROM info WHERE id=5<=====成功
DEBUG    root:mysql.py:94 执行SQL语句=====>DELETE FROM users WHERE id=5<=====成功
DEBUG    root:mysql.py:44 执行SQL语句=====>INSERT INTO users(id, username, password) VALUES(5, 'test02', md5('123456'))<=====成功
DEBUG    root:mysql.py:94 执行SQL语句=====>INSERT INTO info(id, name) VALUES(5, '登录密码为空用户')<=====成功
DEBUG    root:mysql.py:94 执行SQL语句=====>DELETE FROM info WHERE name='登录用户名错误用户'<=====成功
DEBUG    root:mysql.py:94 执行SQL语句=====>DELETE FROM users WHERE username='test03'<=====成功
DEBUG    root:mysql.py:94 执行SQL语句=====>DELETE FROM info WHERE id=6<=====成功
DEBUG    root:mysql.py:94 执行SQL语句=====>DELETE FROM users WHERE id=6<=====成功
DEBUG    root:mysql.py:44 执行SQL语句=====>INSERT INTO users(id, username, password) VALUES(6, 'test04', md5('123456'))<=====成功
DEBUG    root:mysql.py:94 执行SQL语句=====>INSERT INTO info(id, name) VALUES(6, '登录密码错误用户')<=====成功
DEBUG    root:mysql.py:94 执行SQL语句=====>DELETE FROM info WHERE name='登录用户名与密码均错误用户'<=====成功
DEBUG    root:mysql.py:94 执行SQL语句=====>DELETE FROM users WHERE username='test05'<=====成功
DEBUG    root:mysql.py:94 执行SQL语句=====>DELETE FROM info WHERE id=8<=====成功
DEBUG    root:mysql.py:94 执行SQL语句=====>DELETE FROM users WHERE id=8<=====成功
DEBUG    root:mysql.py:44 执行SQL语句=====>INSERT INTO users(id, username, password) VALUES(8, 'test15', md5('123456'))<=====成功
DEBUG    root:mysql.py:94 执行SQL语句=====>INSERT INTO info(id, name) VALUES(8, '密码超过限制长度')<=====成功
DEBUG    urllib3.connectionpool:connectionpool.py:227 Starting new HTTP connection (1): 172.16.9.128:80
DEBUG    urllib3.connectionpool:connectionpool.py:452 http://172.16.9.128:80 "POST /apitest/login/ HTTP/1.1" 200 70
DEBUG    root:requeststart.py:22 发起请求的参数为：{'url': 'http://172.16.9.128:80/apitest/login/', 'method': 'post', 'data': {'username': 'test01', 'password': '123456'}}
DEBUG    root:asserts.py:30 Response_Code实际结果为：1000
DEBUG    root:asserts.py:31 Response_Code预期结果为：1000
INFO     root:asserts.py:33 断言Code用例通过！
DEBUG    root:asserts.py:42 Response_Message实际结果为：Usercheck ok
DEBUG    root:asserts.py:43 Response_Message预期结果为：Usercheck ok
INFO     root:asserts.py:45 断言Message用例通过！
DEBUG    root:asserts.py:42 Response_Message实际结果为：登录验证成功
DEBUG    root:asserts.py:43 Response_Message预期结果为：登录验证成功
INFO     root:asserts.py:45 断言Message用例通过！